version: "3.9"

services:
  kekpass:
    restart: always
    build:
      context: ./src
      dockerfile: ../Dockerfile
    command: python3 manage.py runserver 0.0.0.0:31337
    expose:
      - 31337
    ports:
      - "31337:31337"
